### PR TITLE
Updated README to mention React Router v4 support.

### PR DESCRIPTION
**Pull request by visusnet**
Since v4 is supported but not officially mentioned and some people (incl. my team and others in #14) have tested the compatibility, this PR updates the README to incorporate v4.

### CODE REVIEW

**Comment by jfairbank** [comment]
Hi @visusnet.

That's great to hear! I haven't kept up a ton with RR4, but I'm guessing the setup would be slightly different with redux-saga-router? Can you also update the README with an example that uses RR4?

**Comment by visusnet** [comment]
I will add one tomorrow, no problem! :)

**Comment by visusnet** [comment]
@jfairbank I have updated the existing examples. I don't think a dedicated example for v4 is necessary since there are only a few changes necessary (imports, history object creation).

**Comment by jfairbank** [comment]
That works @visusnet. Thanks again!

**Pull request merged**
