### PR TITLE
Fork sagas and cancel them on location change

### PR DESCRIPTION
**Pull request by victorchabbert**
Hey ! This PR follows our discussion in #6.

I tried to handle saga cancellation without adding a new state.
The downside is that I have not figured out a way to test saga cancellation.

### CODE REVIEW

**Comment by jfairbank** [comment]
Great job! I think everything looks good, and I wouldn't worry too much about testing cancelling sagas. That's still a feature I need to better integrate into redux-saga-test-plan.

There is one caveat to this new behavior that I just realized after testing the code out. If a route saga happens to synchronously throw an error, then it can bring down the whole router saga. The `throw` handler of the router saga can't handle forked saga errors due to the asynchronous nature of forked sagas. I believe we're going to need to use `spawn` instead. It's important that users handle errors in their route saga, but I don't want errors to crash the router saga. Because spawned sagas are detached, any errors they have won't affect the parent saga, which is the router saga.

Do you mind changing this to a `spawn` instead?

**Comment by victorchabbert** [comment]
Should be good now !

I'll work on some documentation later on.

**Comment by jfairbank** [comment]
Thanks! I'll leave this unmerged for now if you plan to add on documentation. I would gladly appreciate it :) No pressure to do so, though.

**Comment by victorchabbert** [comment]
No worries, let me know if I have to change anything!

**Comment by jfairbank** [comment]
Looks good! Thanks!

**Comment by jfairbank** [comment]
FYI, out in v2.0.0 on npm now.

**Pull request merged**
